version: '3.4'
services:
  mssql:
      image: "mcr.microsoft.com/azure-sql-edge"
      ports:
          - '1433:1433'
      environment:
          - ACCEPT_EULA=1
          - MSSQL_SA_PASSWORD=!DbSamples142314_
networks:
  default:    
    external: true
    name : snnnetwork